source 'https://rubygems.org'
gem 'rails', '3.2.13'
gem 'sqlite3'
gem 'jquery-rails'
gem 'bootstrap-sass'
gem 'figaro'
gem 'haml-rails'
gem 'thin'
# gem 'wicked_pdf'
gem 'princely'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
group :development do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_19, :rbx]
  gem 'html2haml'
  gem 'quiet_assets'
end
group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'email_spec'
end
